name: Pull Request Ready for Review
on:
  pull_request:
    types: [ready_for_review]

jobs:
  moveToReadyForReview:
    runs-on: ubuntu-latest
    steps:
      - name: Move to "Ready for review" column
        if: github.event.pull_request.draft == false
        uses: alex-page/github-project-automation-plus@v0.2.3
        with:
          project: Artemis Development
          column: Ready for review
          repo-token: ${{ secrets.GH_TOKEN_ADD_TO_PROJECT }}

  requestReviews:
    runs-on: ubuntu-latest
    steps:
      - name: Request Reviews from @ls1intum/artemis Team
        uses: rowi1de/auto-assign-review-teams@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          teams: "@ls1intum/artemis"
          skip-with-manual-reviewers: 5
